drop extension if exists "pg_net";


  create table "public"."config" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text,
    "value" json
      );


alter table "public"."config" enable row level security;


  create table "public"."invite_code" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "code" text,
    "person" text,
    "expires_at" text,
    "is_used" text
      );


alter table "public"."invite_code" enable row level security;


  create table "public"."profiles" (
    "id" uuid not null,
    "updated_at" timestamp with time zone default now(),
    "username" text,
    "email" text,
    "avatar_url" text,
    "role" text default 'admin'::text,
    "desc" text default 'I''m mpk broo!'::text
      );


alter table "public"."profiles" enable row level security;


  create table "public"."seminar_photo" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text,
    "deskripsi" text,
    "tgl" text,
    "img_url" text
      );


alter table "public"."seminar_photo" enable row level security;

CREATE UNIQUE INDEX config_pkey ON public.config USING btree (id);

CREATE UNIQUE INDEX invite_code_pkey ON public.invite_code USING btree (id);

CREATE UNIQUE INDEX profiles_email_key ON public.profiles USING btree (email);

CREATE UNIQUE INDEX profiles_pkey ON public.profiles USING btree (id);

CREATE UNIQUE INDEX profiles_username_key ON public.profiles USING btree (username);

CREATE UNIQUE INDEX seminar_photo_pkey ON public.seminar_photo USING btree (id);

alter table "public"."config" add constraint "config_pkey" PRIMARY KEY using index "config_pkey";

alter table "public"."invite_code" add constraint "invite_code_pkey" PRIMARY KEY using index "invite_code_pkey";

alter table "public"."profiles" add constraint "profiles_pkey" PRIMARY KEY using index "profiles_pkey";

alter table "public"."seminar_photo" add constraint "seminar_photo_pkey" PRIMARY KEY using index "seminar_photo_pkey";

alter table "public"."profiles" add constraint "profiles_email_key" UNIQUE using index "profiles_email_key";

alter table "public"."profiles" add constraint "profiles_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."profiles" validate constraint "profiles_id_fkey";

alter table "public"."profiles" add constraint "profiles_username_key" UNIQUE using index "profiles_username_key";

alter table "public"."profiles" add constraint "username_length" CHECK ((char_length(username) >= 3)) not valid;

alter table "public"."profiles" validate constraint "username_length";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
begin
  insert into public.profiles (id, username, email, avatar_url, role)
  values (new.id, new.raw_user_meta_data->>'username', new.raw_user_meta_data->>'email', new.raw_user_meta_data->>'avatar_url', new.raw_user_meta_data->>'role');
  return new;
end;
$function$
;

grant delete on table "public"."config" to "anon";

grant insert on table "public"."config" to "anon";

grant references on table "public"."config" to "anon";

grant select on table "public"."config" to "anon";

grant trigger on table "public"."config" to "anon";

grant truncate on table "public"."config" to "anon";

grant update on table "public"."config" to "anon";

grant delete on table "public"."config" to "authenticated";

grant insert on table "public"."config" to "authenticated";

grant references on table "public"."config" to "authenticated";

grant select on table "public"."config" to "authenticated";

grant trigger on table "public"."config" to "authenticated";

grant truncate on table "public"."config" to "authenticated";

grant update on table "public"."config" to "authenticated";

grant delete on table "public"."config" to "service_role";

grant insert on table "public"."config" to "service_role";

grant references on table "public"."config" to "service_role";

grant select on table "public"."config" to "service_role";

grant trigger on table "public"."config" to "service_role";

grant truncate on table "public"."config" to "service_role";

grant update on table "public"."config" to "service_role";

grant delete on table "public"."invite_code" to "anon";

grant insert on table "public"."invite_code" to "anon";

grant references on table "public"."invite_code" to "anon";

grant select on table "public"."invite_code" to "anon";

grant trigger on table "public"."invite_code" to "anon";

grant truncate on table "public"."invite_code" to "anon";

grant update on table "public"."invite_code" to "anon";

grant delete on table "public"."invite_code" to "authenticated";

grant insert on table "public"."invite_code" to "authenticated";

grant references on table "public"."invite_code" to "authenticated";

grant select on table "public"."invite_code" to "authenticated";

grant trigger on table "public"."invite_code" to "authenticated";

grant truncate on table "public"."invite_code" to "authenticated";

grant update on table "public"."invite_code" to "authenticated";

grant delete on table "public"."invite_code" to "service_role";

grant insert on table "public"."invite_code" to "service_role";

grant references on table "public"."invite_code" to "service_role";

grant select on table "public"."invite_code" to "service_role";

grant trigger on table "public"."invite_code" to "service_role";

grant truncate on table "public"."invite_code" to "service_role";

grant update on table "public"."invite_code" to "service_role";

grant delete on table "public"."profiles" to "anon";

grant insert on table "public"."profiles" to "anon";

grant references on table "public"."profiles" to "anon";

grant select on table "public"."profiles" to "anon";

grant trigger on table "public"."profiles" to "anon";

grant truncate on table "public"."profiles" to "anon";

grant update on table "public"."profiles" to "anon";

grant delete on table "public"."profiles" to "authenticated";

grant insert on table "public"."profiles" to "authenticated";

grant references on table "public"."profiles" to "authenticated";

grant select on table "public"."profiles" to "authenticated";

grant trigger on table "public"."profiles" to "authenticated";

grant truncate on table "public"."profiles" to "authenticated";

grant update on table "public"."profiles" to "authenticated";

grant delete on table "public"."profiles" to "service_role";

grant insert on table "public"."profiles" to "service_role";

grant references on table "public"."profiles" to "service_role";

grant select on table "public"."profiles" to "service_role";

grant trigger on table "public"."profiles" to "service_role";

grant truncate on table "public"."profiles" to "service_role";

grant update on table "public"."profiles" to "service_role";

grant delete on table "public"."seminar_photo" to "anon";

grant insert on table "public"."seminar_photo" to "anon";

grant references on table "public"."seminar_photo" to "anon";

grant select on table "public"."seminar_photo" to "anon";

grant trigger on table "public"."seminar_photo" to "anon";

grant truncate on table "public"."seminar_photo" to "anon";

grant update on table "public"."seminar_photo" to "anon";

grant delete on table "public"."seminar_photo" to "authenticated";

grant insert on table "public"."seminar_photo" to "authenticated";

grant references on table "public"."seminar_photo" to "authenticated";

grant select on table "public"."seminar_photo" to "authenticated";

grant trigger on table "public"."seminar_photo" to "authenticated";

grant truncate on table "public"."seminar_photo" to "authenticated";

grant update on table "public"."seminar_photo" to "authenticated";

grant delete on table "public"."seminar_photo" to "service_role";

grant insert on table "public"."seminar_photo" to "service_role";

grant references on table "public"."seminar_photo" to "service_role";

grant select on table "public"."seminar_photo" to "service_role";

grant trigger on table "public"."seminar_photo" to "service_role";

grant truncate on table "public"."seminar_photo" to "service_role";

grant update on table "public"."seminar_photo" to "service_role";


  create policy "Enable insert for authenticated users only"
  on "public"."config"
  as permissive
  for insert
  to authenticated
with check (true);



  create policy "Enable read access for all users"
  on "public"."config"
  as permissive
  for select
  to public
using (true);



  create policy "Enable update"
  on "public"."config"
  as permissive
  for update
  to authenticated
using (true)
with check (true);



  create policy "Enable insert for authenticated users only"
  on "public"."invite_code"
  as permissive
  for insert
  to authenticated
with check (true);



  create policy "Enable read access for all users"
  on "public"."invite_code"
  as permissive
  for select
  to public
using (true);



  create policy "enable update"
  on "public"."invite_code"
  as permissive
  for update
  to public
using (true)
with check (true);



  create policy "Public profiles are viewable by everyone."
  on "public"."profiles"
  as permissive
  for select
  to public
using (true);



  create policy "Users can insert their own profile."
  on "public"."profiles"
  as permissive
  for insert
  to public
with check ((( SELECT auth.uid() AS uid) = id));



  create policy "Users can update own profile."
  on "public"."profiles"
  as permissive
  for update
  to public
using ((( SELECT auth.uid() AS uid) = id));



  create policy "Enable delete"
  on "public"."seminar_photo"
  as permissive
  for delete
  to authenticated
using (true);



  create policy "Enable insert for authenticated users only"
  on "public"."seminar_photo"
  as permissive
  for insert
  to authenticated
with check (true);



  create policy "Enable read access for all users"
  on "public"."seminar_photo"
  as permissive
  for select
  to public
using (true);



  create policy "Enable update"
  on "public"."seminar_photo"
  as permissive
  for update
  to authenticated
using (true)
with check (true);


CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


  create policy "Anyone can upload an avatar."
  on "storage"."objects"
  as permissive
  for insert
  to public
with check ((bucket_id = 'avatars'::text));



  create policy "Avatar images are publicly accessible."
  on "storage"."objects"
  as permissive
  for select
  to public
using ((bucket_id = 'avatars'::text));



  create policy "Enable delete, upload, and update wqc4c1_0"
  on "storage"."objects"
  as permissive
  for insert
  to authenticated
with check ((bucket_id = 'seminar'::text));



  create policy "Enable delete, upload, and update wqc4c1_1"
  on "storage"."objects"
  as permissive
  for select
  to authenticated
using ((bucket_id = 'seminar'::text));



  create policy "Enable delete, upload, and update wqc4c1_2"
  on "storage"."objects"
  as permissive
  for update
  to authenticated
using ((bucket_id = 'seminar'::text));



  create policy "Enable delete, upload, and update wqc4c1_3"
  on "storage"."objects"
  as permissive
  for delete
  to authenticated
using ((bucket_id = 'seminar'::text));



  create policy "Enable read wqc4c1_0"
  on "storage"."objects"
  as permissive
  for select
  to public
using ((bucket_id = 'seminar'::text));



